delete from tmp_work_db.comm_nps_sb_trans_tmp2 all;

insert into tmp_work_db.comm_nps_sb_trans_tmp2
(
		evnt_dt,
		evnt_dts,
		cnsld_src_txn_id,
		cnsld_src_txn_bu_id,
		so_nbr,
		so_bu_id,
		so_lcl_chnl_cd,
		so_dt,
		so_inv_dt,
		qte_nbr,
		qte_bu_id,
		qte_lcl_chnl_cd,
		qte_dt,
		prim_sls_assoc_nbr,
		secnd_sls_assoc_nbr,
		sys_itm_cls_nm,
		sys_flg,
		snp_flg,
		svcs_flg,
		sls_chnl_cd,
		tot_revn_disc_amt,
		ord_dispos_stat_cd,
		sls_type_cd,
		cust_bu_id,
		cust_lcl_chnl_cd,
		bilt_cust_nbr,
		bilt_src_cust_id,
		bilt_addr_seq_id,
		bilt_cntct_id,
		shpto_cust_nbr,
		shpto_src_cust_id,
		shpto_addr_seq_id,
		shpto_cntct_id
)
	select
		tmp1.evnt_dt,
		tmp1.evnt_dts,
		tmp1.cnsld_src_txn_id,
		tmp1.cnsld_src_txn_bu_id,
		tmp1.so_nbr,
		tmp1.so_bu_id,
		tmp1.so_lcl_chnl_cd,
		tmp1.so_dt,
		tmp1.so_inv_dt,
		tmp1.qte_nbr,
		tmp1.qte_bu_id,
		tmp1.qte_lcl_chnl_cd,
		tmp1.qte_dt,
		tmp1.prim_sls_assoc_nbr,
		tmp1.secnd_sls_assoc_nbr,
		tmp1.sys_itm_cls_nm,
		tmp1.sys_flg,
		tmp1.snp_flg,
		tmp1.svcs_flg,
		tmp1.sls_chnl_cd,
		tmp1.tot_revn_disc_amt,
		tmp1.ord_dispos_stat_cd,
		tmp1.sls_type_cd,
		tmp1.cust_bu_id,
		tmp1.cust_lcl_chnl_cd,
		tmp1.bilt_cust_nbr,
		tmp1.bilt_src_cust_id,
		tmp1.bilt_addr_seq_id,
		tmp1.bilt_cntct_id,
		tmp1.shpto_cust_nbr,
		tmp1.shpto_src_cust_id,
		tmp1.shpto_addr_seq_id,
		tmp1.shpto_cntct_id
	from tmp_work_db.comm_nps_sb_trans_tmp1 tmp1
	inner join (select cust_bu_id, bilt_cust_nbr, shpto_cust_nbr from tmp_work_db.comm_nps_sb_trans_tmp1 group by 1,2,3 having sum(tot_revn_disc_amt) >= 1000) tmp2
	on tmp1.cust_bu_id = tmp2.cust_bu_id and tmp1.bilt_cust_nbr = tmp2.bilt_cust_nbr and tmp1.shpto_cust_nbr = tmp2.shpto_cust_nbr
	where tmp1.sys_flg = 'Y'
	qualify rank() over (partition by tmp1.cust_bu_id, tmp1.bilt_cust_nbr, tmp1.shpto_cust_nbr order by tmp1.so_nbr desc) = 1;
